export const API_ENDPOINT = {
    auth: {
        login: '/auth/login',
        requestOTP: '/auth/request-otp',
        verifyOTP: '/auth/verify-otp',
        register: '/auth/register',
        refreshToken: '/auth/processNewToken',
        changePassword: '/auth/change-password',
        logout: '/auth/logout',
    },
    user: {
        getMe: '/users/me',
        updateProfile: '/users/profile',
        uploadAvatar: '/users/avatar',
    },
    workspace: {
        getAllWorkspaces: '/workspaces',
        getArchivedWorkspaces: '/workspaces/archived',
        getWorkspaceById: '/workspaces/:id',
        createWorkspace: '/workspaces',
        updateWorkspace: '/workspaces/:id',
        deleteWorkspace: '/workspaces/:id',
        archiveWorkspace: '/workspaces/:id/archive',
        reopenWorkspace: '/workspaces/:id/reopen',
        getWorkspaceMembers: '/workspaces/:id/members',
        addWorkspaceMember: '/workspaces/:id/members',
        deleteWorkspaceMember: '/workspaces/:id/members/:userId',
        getWorkspaceRoles: '/workspaces/:id/roles',
        createWorkspaceRole: '/workspaces/:id/roles',
        updateWorkspaceRole: '/workspaces/:id/roles/:roleId',
        deleteWorkspaceRole: '/workspaces/:id/roles/:roleId',
        updateMemberRole: '/workspaces/:id/members/:userId',
    },
    board: {
        getBoardsByWorkspaceId: '/workspaces/:id/boards',
        createBoardFromWorkspace: '/workspaces/:id/boards',
        getBoardById: '/boards/:boardId',
        updateBoard: '/boards/:boardId',
        deleteBoard: '/boards/:boardId',
        reopenBoard: '/boards/:id/reopen',
        joinBoardByLink: '/boards/join',
        createBoardJoinLink: 'boards/:id/invite/link',
        revokeBoardJoinLink: 'boards/:id/invite/link/:linkId/revoke',
        inviteByEmail: 'boards/:id/invite/email',
        getBoardMembers: '/boards/:id/members',
        getBoardLists: '/boards/:id/lists',
        createList: '/boards/:id/lists',
        getArchiveLists: '/boards/:boardId/lists/archived',
        changeOwnerBoard: '/boards/:id/change-owner',
    },
    list: {
        reorder: '/lists/reorder',
        copy: '/lists/copy',
        move: '/lists/move',
        editListName: '/lists/:listId/name',
        archive: '/lists/:listId/archive',
        reopen: '/lists/:listId/reopen',
        createCard: '/lists/:listId/cards',
    },
    card: {
        getCardByListId: '/lists/:listId/cards',
        getArchiveCards: '/lists/:listId/cards/archived',
        getCardMembers: '/cards/:id/members',
        getChecklists: '/cards/:id/checklists',
        assignMember: '/cards/:id/members',
        createChecklist: '/cards/:id/checklists',
        removeMember: '/cards/:id/members',
        updateCard: '/cards/:id',
        archive: '/cards/:id/archive',
        reopen: '/cards/:id/reopen',
        reorder: '/cards/reorder',
        copy: '/cards/copy',
        move: '/cards/move',
    },
    checklist: {
        createChecklist: '/cards/:id/checklists',
        getChecklistsByCardId: '/cards/:id/checklists',
        updateChecklist: '/checklists/:checklistId',
        deleteChecklist: '/checklists/:checklistId',
    },
    checklistItem: {
        createChecklistItem: '/checklists/:checklistId/items',
        getChecklistItems: '/checklists/:checklistId/items',
        updateStatus: '/checklist-items/:itemId/status',
        updateContent: '/checklist-items/:itemId/content',
        delete: '/checklist-items/:itemId',
    },
    permission: {
        getAllPermissions: '/permissions',
    }

} as const;